substitutions:
  name: seplos-bms
  battery_bank0: "${name} bank 0"
  battery_bank1: "${name} bank 1"
  battery_bank2: "${name} bank 2"
  device_description: "Monitor a Seplos BMS via RS485"
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-seplos-bms"
    version: 1.3.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  id: uart_0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  # The increased RX buffer size is important because
  # the full BMS response must fit into the buffer
  rx_buffer_size: 384

seplos_modbus:
  id: modbus0
  uart_id: uart_0

seplos_bms:
  - id: battery_bank0
    # Dip switch configuration of the first pack / address 0x01
    #  8    7    6    5    4    3    2   1
    # off, off, off, off, off, off, off, on
    address: 0x01
    # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
    protocol_version: 0x20
    seplos_modbus_id: modbus0
    update_interval: 10s
  - id: battery_bank1
    # Dip switch configuration of the second pack / address 0x02
    #  8    7    6    5    4    3   2    1
    # off, off, off, off, off, off, on, off
    address: 0x02
    # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
    protocol_version: 0x20
    seplos_modbus_id: modbus0
    update_interval: 10s
  - id: battery_bank2
    # Dip switch configuration of the third pack / address 0x03
    #  8    7    6    5    4    3   2   1
    # off, off, off, off, off, off, on, on
    address: 0x03
    # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
    protocol_version: 0x20
    seplos_modbus_id: modbus0
    update_interval: 10s

sensor:
  - platform: seplos_bms
    seplos_bms_id: battery_bank0
    min_cell_voltage:
      name: "${battery_bank0} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank0} max cell voltage"
    delta_cell_voltage:
      name: "${battery_bank0} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank0} average cell voltage"
    total_voltage:
      name: "${battery_bank0} total voltage"
    current:
      name: "${battery_bank0} current"
    power:
      name: "${battery_bank0} power"
    state_of_charge:
      name: "${battery_bank0} state of charge"
    # Alarm event bitmask sensors
    alarm_event1_bitmask:
      name: "${battery_bank0} alarm event 1 bitmask"
    alarm_event2_bitmask:
      name: "${battery_bank0} alarm event 2 bitmask"
    alarm_event3_bitmask:
      name: "${battery_bank0} alarm event 3 bitmask"
    alarm_event4_bitmask:
      name: "${battery_bank0} alarm event 4 bitmask"
    alarm_event5_bitmask:
      name: "${battery_bank0} alarm event 5 bitmask"
    alarm_event6_bitmask:
      name: "${battery_bank0} alarm event 6 bitmask"
    alarm_event7_bitmask:
      name: "${battery_bank0} alarm event 7 bitmask"
    alarm_event8_bitmask:
      name: "${battery_bank0} alarm event 8 bitmask"
    # Balancing and disconnection sensors
    balancing_bitmask:
      name: "${battery_bank0} balancing bitmask"
    disconnection_bitmask:
      name: "${battery_bank0} disconnection bitmask"
    system_status_bitmask:
      name: "${battery_bank0} system status bitmask"

  - platform: seplos_bms
    seplos_bms_id: battery_bank1
    min_cell_voltage:
      name: "${battery_bank1} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank1} max cell voltage"
    delta_cell_voltage:
      name: "${battery_bank1} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank1} average cell voltage"
    total_voltage:
      name: "${battery_bank1} total voltage"
    current:
      name: "${battery_bank1} current"
    power:
      name: "${battery_bank1} power"
    state_of_charge:
      name: "${battery_bank1} state of charge"
    # Alarm event bitmask sensors
    alarm_event1_bitmask:
      name: "${battery_bank1} alarm event 1 bitmask"
    alarm_event2_bitmask:
      name: "${battery_bank1} alarm event 2 bitmask"
    alarm_event3_bitmask:
      name: "${battery_bank1} alarm event 3 bitmask"
    alarm_event4_bitmask:
      name: "${battery_bank1} alarm event 4 bitmask"
    alarm_event5_bitmask:
      name: "${battery_bank1} alarm event 5 bitmask"
    alarm_event6_bitmask:
      name: "${battery_bank1} alarm event 6 bitmask"
    alarm_event7_bitmask:
      name: "${battery_bank1} alarm event 7 bitmask"
    alarm_event8_bitmask:
      name: "${battery_bank1} alarm event 8 bitmask"
    # Balancing and disconnection sensors
    balancing_bitmask:
      name: "${battery_bank1} balancing bitmask"
    disconnection_bitmask:
      name: "${battery_bank1} disconnection bitmask"
    system_status_bitmask:
      name: "${battery_bank1} system status bitmask"

  - platform: seplos_bms
    seplos_bms_id: battery_bank2
    min_cell_voltage:
      name: "${battery_bank2} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank2} max cell voltage"
    delta_cell_voltage:
      name: "${battery_bank2} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank2} average cell voltage"
    total_voltage:
      name: "${battery_bank2} total voltage"
    current:
      name: "${battery_bank2} current"
    power:
      name: "${battery_bank2} power"
    state_of_charge:
      name: "${battery_bank2} state of charge"
    # Alarm event bitmask sensors
    alarm_event1_bitmask:
      name: "${battery_bank2} alarm event 1 bitmask"
    alarm_event2_bitmask:
      name: "${battery_bank2} alarm event 2 bitmask"
    alarm_event3_bitmask:
      name: "${battery_bank2} alarm event 3 bitmask"
    alarm_event4_bitmask:
      name: "${battery_bank2} alarm event 4 bitmask"
    alarm_event5_bitmask:
      name: "${battery_bank2} alarm event 5 bitmask"
    alarm_event6_bitmask:
      name: "${battery_bank2} alarm event 6 bitmask"
    alarm_event7_bitmask:
      name: "${battery_bank2} alarm event 7 bitmask"
    alarm_event8_bitmask:
      name: "${battery_bank2} alarm event 8 bitmask"
    # Balancing and disconnection sensors
    balancing_bitmask:
      name: "${battery_bank2} balancing bitmask"
    disconnection_bitmask:
      name: "${battery_bank2} disconnection bitmask"
    system_status_bitmask:
      name: "${battery_bank2} system status bitmask"

binary_sensor:
  - platform: seplos_bms
    seplos_bms_id: battery_bank0
    online_status:
      name: "${battery_bank0} online status"
    charging:
      name: "${battery_bank0} charging"
    discharging:
      name: "${battery_bank0} discharging"
    voltage_protection:
      name: "${battery_bank0} voltage protection"
    temperature_protection:
      name: "${battery_bank0} temperature protection"
    current_protection:
      name: "${battery_bank0} current protection"
    soc_protection:
      name: "${battery_bank0} soc protection"
    balancing:
      name: "${battery_bank0} balancing"

  - platform: seplos_bms
    seplos_bms_id: battery_bank1
    online_status:
      name: "${battery_bank1} online status"
    charging:
      name: "${battery_bank1} charging"
    discharging:
      name: "${battery_bank1} discharging"
    voltage_protection:
      name: "${battery_bank1} voltage protection"
    temperature_protection:
      name: "${battery_bank1} temperature protection"
    current_protection:
      name: "${battery_bank1} current protection"
    soc_protection:
      name: "${battery_bank1} soc protection"
    balancing:
      name: "${battery_bank1} balancing"

  - platform: seplos_bms
    seplos_bms_id: battery_bank2
    online_status:
      name: "${battery_bank2} online status"
    charging:
      name: "${battery_bank2} charging"
    discharging:
      name: "${battery_bank2} discharging"
    voltage_protection:
      name: "${battery_bank2} voltage protection"
    temperature_protection:
      name: "${battery_bank2} temperature protection"
    current_protection:
      name: "${battery_bank2} current protection"
    soc_protection:
      name: "${battery_bank2} soc protection"
    balancing:
      name: "${battery_bank2} balancing"

text_sensor:
  - platform: seplos_bms
    seplos_bms_id: battery_bank0
    alarms:
      name: "${battery_bank0} alarms"

  - platform: seplos_bms
    seplos_bms_id: battery_bank1
    alarms:
      name: "${battery_bank1} alarms"

  - platform: seplos_bms
    seplos_bms_id: battery_bank2
    alarms:
      name: "${battery_bank2} alarms"
