substitutions:
  name: seplos-bms
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
logger:

uart:
  id: uart0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  rx_buffer_size: 384
  debug:
    direction: BOTH
#    after:
#      delimiter: "\r"
#    sequence:
#      - lambda: UARTDebug::log_string(direction, bytes);

seplos_modbus:
  id: modbus0
  uart_id: uart0

seplos_bms:
  id: bms0
  seplos_modbus_id: modbus0

binary_sensor:
  - platform: seplos_bms
    fan_running:
      name: "${name} fan running"

sensor:
  - platform: seplos_bms
    temperature:
      name: "${name} temperature"

text_sensor:
  - platform: seplos_bms
    errors:
      name: "${name} errors"
